// GENERATED by @edgedb/generate v0.5.6

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $TokenλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "symbol": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "address": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "updatedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "metrics": $.LinkDesc<$TokenMetrics, $.Cardinality.One, {}, true, false,  false, false>;
  "price": $.LinkDesc<$TokenPrices, $.Cardinality.One, {}, true, false,  false, false>;
}>;
type $Token = $.ObjectType<"default::Token", $TokenλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {price: {__element__: $TokenPrices, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {address: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {metrics: {__element__: $TokenMetrics, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Token = $.makeType<$Token>(_.spec, "f8c36ff0-d774-11ef-b283-f34861a02328", _.syntax.literal);

const Token: $.$expr_PathNode<$.TypeSet<$Token, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Token, $.Cardinality.Many), null);

export type $TokenMetricsλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "timestamp": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "holderConcentration": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "bundlerActivity": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "liquidityScore": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "marketCapRisk": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "metadata": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, true>;
  "priceVolatility": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "accumulationRate": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "sellPressure": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "volumeAnomaly": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "isRugPull": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "holders": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "currentPrice": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "isHoneyPot": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "stealthAccumulation": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "totalSupply": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "tokenAddress": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "suspiciousPattern": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "<metrics[is Token]": $.LinkDesc<$Token, $.Cardinality.AtMostOne, {}, true, false,  false, false>;
  "<metrics": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $TokenMetrics = $.ObjectType<"default::TokenMetrics", $TokenMetricsλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $TokenMetrics = $.makeType<$TokenMetrics>(_.spec, "f8c91ea0-d774-11ef-aafa-05f3d49414bc", _.syntax.literal);

const TokenMetrics: $.$expr_PathNode<$.TypeSet<$TokenMetrics, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($TokenMetrics, $.Cardinality.Many), null);

export type $TokenPricesλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "timestamp": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "marketCap": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "price": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "volume24h": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "liquidity": $.PropertyDesc<_std.$decimal, $.Cardinality.One, false, false, false, true>;
  "tokenAddress": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<price[is Token]": $.LinkDesc<$Token, $.Cardinality.AtMostOne, {}, true, false,  false, false>;
  "<price": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $TokenPrices = $.ObjectType<"default::TokenPrices", $TokenPricesλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $TokenPrices = $.makeType<$TokenPrices>(_.spec, "f8ccb8d0-d774-11ef-86a4-896b93af85b7", _.syntax.literal);

const TokenPrices: $.$expr_PathNode<$.TypeSet<$TokenPrices, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($TokenPrices, $.Cardinality.Many), null);



export { $Token, Token, $TokenMetrics, TokenMetrics, $TokenPrices, TokenPrices };

type __defaultExports = {
  "Token": typeof Token;
  "TokenMetrics": typeof TokenMetrics;
  "TokenPrices": typeof TokenPrices
};
const __defaultExports: __defaultExports = {
  "Token": Token,
  "TokenMetrics": TokenMetrics,
  "TokenPrices": TokenPrices
};
export default __defaultExports;
